### ISSUE TITLE
module/PRO0.php Line 17

### ISSUE THREAD

**Issue by ckrudelux** [Level-2/Axel#4]
If the class and namespace is of the same name this would not work.
Like if I would try to load ```\Dice\Dice```

Current:
```$className = str_replace($this->namespace, '', $className);```

Should be something like this:
```$className = trim(substr($className, strlen($this->namespace)), '\\');```

**Comment by TomBZombie** [comment]
Yes, you're right. Well spotted!

**Comment by ckrudelux** [comment]
Thank you, but I notice someone made a pull request about this after I posted this issue but the solution assumes namespaces are only one level deep, so not much of a fix really.
